{
  "hash": "0a3b2658ccc9c1ff819875028a47069f",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Survey Data, Censuses, and Age Standardization in Health Sciences\"\nauthor: \"Sudipto Banerjee<br><em>Department of Biostatistics<br>Department of Statistics & Data Science<br>Institute of the Environment & Sustainability<br>UCLA</em>\"\noutput:\n  html_document:\n    toc: true\n    toc_float:\n      collapsed: true\n      smooth_scroll: true\n    toc_depth: 3\n    number_sections: true\n    theme: flatly\n    self_contained: true\nformat:\n  html:\n    page-layout: full\n    fontsize: 14.5px\n    toc: true\n    toc-location: left\n    toc-expand: 1\n    toc-depth: 3\n    number-sections: true\n    theme: flatly\n    code-copy: hover\n    embed-resources: true\n---\n\n<div style=\"display:none;\">\n$$\\newcommand{\\T}{\\mathrm{\\scriptscriptstyle T}}$$\n</div>\n\n<style>\n.main-container {\n  margin-left: 280px !important;\n  max-width: 95% !important;\n}\n\ndiv.tocify {\n  width: 250px !important;\n}\n\n#quarto-document-content {\n  padding-left: 2rem !important;\n  padding-right: 2rem !important;\n  max-width: 1500px !important;\n}\n\nli > p {\n  margin-bottom: 0px !important;\n}\nli > ul {\n  margin-top: 2px !important;\n}\n\ndetails.proof-box {\n  margin-top: 1em;\n  margin-bottom: 1.2em;\n  padding: 0.8em 1.2em;\n  background-color: #f8fafc;\n  border: 1px solid #cbd5e1;\n  border-radius: 6px;\n  box-shadow: 0 1px 3px rgba(0,0,0,0.05);\n  overflow-x: auto;\n}\n\n#quarto-content details.proof-box {\n  margin-left: -2em;\n  margin-right: -2em;\n  padding-left: 1.5em;\n  padding-right: 1.5em;\n}\n\ndetails.proof-box summary {\n  font-weight: 600;\n  color: #1e293b;\n  cursor: pointer;\n  outline: none;\n}\n\ndetails.proof-box summary:hover {\n  color: #2563eb;\n}\n\ndetails.proof-box[open] summary {\n  border-bottom: 1px solid #e2e8f0;\n  padding-bottom: 0.5em;\n  margin-bottom: 0.8em;\n}\n\n.proof-body {\n  padding-top: 0.4em;\n  line-height: 1.6;\n}\n\n.pde-box {\n  background-color: #f0f9ff;\n  border-left: 4px solid #0284c7;\n  padding: 1em 1.2em;\n  margin: 1.2em 0;\n  border-radius: 0 6px 6px 0;\n}\n\n.equation-box {\n  background-color: #f0fdf4;\n  border-left: 4px solid #16a34a;\n  padding: 1em 1.2em;\n  margin: 1.2em 0;\n  border-radius: 0 6px 6px 0;\n}\n\n.equation-title {\n  font-weight: 700;\n  color: #0f172a;\n  margin-bottom: 0.4em;\n  font-size: 0.95em;\n  text-transform: uppercase;\n  letter-spacing: 0.05em;\n}\n\n/* Bottom Collapse Button Styling */\n.proof-close-container {\n  display: flex;\n  justify-content: flex-end;\n  margin-top: 1.2em;\n  padding-top: 0.6em;\n  border-top: 1px dashed #cbd5e1;\n}\n\n.proof-close-btn {\n  background-color: #f1f5f9;\n  color: #475569;\n  border: 1px solid #cbd5e1;\n  border-radius: 20px;\n  padding: 4px 14px;\n  font-size: 0.85em;\n  font-weight: 500;\n  cursor: pointer;\n  display: inline-flex;\n  align-items: center;\n  gap: 6px;\n  transition: all 0.2s ease-in-out;\n}\n\n.proof-close-btn:hover {\n  background-color: #e2e8f0;\n  color: #0f172a;\n  border-color: #94a3b8;\n  transform: translateY(-1px);\n}\n</style>\n\n\n\n# Introduction: Survey Data in Public Health and Data Science\n\nModern public health research, epidemiological surveillance, and health policy depend heavily on probability sampling and survey design. Whether investigating disease prevalence, tracking environmental exposures, or evaluating healthcare utilization, collecting data from every individual in a target population is rarely feasible.\n\nIn this introductory lecture, we explore the foundational role of **censuses** and **sample surveys** in health statistics. We examine landmark health surveys, learn how censuses provide vital population denominators, and investigate **age-standardization**—a critical epidemiological method that serves as our conceptual gateway to **stratified sampling**.\n\n---\n\n# Censuses vs. Sample Surveys in Health Research\n\nPopulation data collection broadly falls into two paradigms: complete enumerations (**censuses**) and probabilistic subset selections (**sample surveys**).\n\n::: {.equation-box}\n::: {.equation-title}\nKey Concepts: Censuses and Sample Surveys\n:::\n\n* **Census (Complete Enumeration):** An attempt to collect data from *every* unit in a well-defined finite target population $U = \\{1, 2, \\dots, N\\}$.\n\n* **Sample Survey:** A systematic process of selecting a subset $S \\subset U$ of size $n < N$ according to a pre-specified probabilistic sampling design $P(S)$.\n:::\n\n## Major US Health Surveys and Data Systems\n\nHealth data scientists routinely analyze large-scale national surveys. Four primary systems illustrate different sampling methodologies and objectives:\n\n1. **National Health and Nutrition Examination Survey (NHANES):**\n\n   * *Structure:* Continuous multi-stage probability sample of the non-institutionalized US civilian population.\n\n   * *Unique Feature:* Combines household interviews with standardized physical examinations and laboratory tests in Mobile Examination Centers (MECs).\n\n2. **Behavioral Risk Factor Surveillance System (BRFSS):**\n\n   * *Structure:* World's largest continuously conducted health survey, administered by state health departments with CDC support.\n\n   * *Unique Feature:* Random-digit-dialed (RDD) landline and cellular telephone survey measuring behavioral risk factors (e.g., smoking, physical activity, alcohol consumption).\n\n3. **National Health Interview Survey (NHIS):**\n\n   * *Structure:* Cross-sectional household interview survey using complex multi-stage cluster sampling.\n\n   * *Unique Feature:* Primary source of national data on healthcare access, chronic conditions, and disability.\n\n4. **US Decennial Census & American Community Survey (ACS):**\n\n   * *Structure:* The Decennial Census provides complete population counts ($N$), while the ACS provides continuous rolling sample estimates of demographic and socio-economic characteristics.\n\n   * *Unique Feature:* Supplies the **population denominators** ($P$) required to calculate disease rates, incidence, and mortality across demographic subgroups and geographic boundaries.\n\n---\n\n# Population Denominators and Crude Rates\n\nIn epidemiology and vital statistics, measuring disease occurrence requires placing health events (numerators) in context with the population at risk (denominators).\n\n::: {.pde-box}\n**Definition: Crude Mortality Rate (CMR)**  \nLet $D$ denote the total number of deaths recorded in a region during a given time period, and let $P$ denote the total person-time at risk (or mid-year total population size). The Crude Mortality Rate is defined as:\n\n$$\\text{CMR} = \\frac{D}{P}$$\n\nCommonly expressed per $1,000$ or $100,000$ person-years.\n:::\n\n## The Danger of Crude Rate Comparisons: Simpson's Paradox\n\nDirectly comparing crude mortality rates across different populations (e.g., two counties, states, or countries) can lead to profoundly misleading conclusions when the populations differ in underlying demographic structures—most notably, **age distribution**.\n\nBecause overall mortality risk increases dramatically with age, a population with a large proportion of elderly residents (e.g., Florida) will naturally exhibit a higher crude mortality rate than a population with a younger demographic profile (e.g., Utah), even if the younger population actually experiences higher mortality rates within *every single age bracket*.\n\nThis phenomenon is a classical manifestation of **confounding by age** (or **Simpson's Paradox**). To make meaningful comparisons, we must adjust for age differences using **age standardization**.\n\n---\n\n## A Concrete Numerical Illustration of Simpson's Paradox\n\nTo see Simpson's Paradox in action, consider two communities with equal total populations of $N = 100,000$:\n\n* **County A:** An older retiree community where $80\\%$ of the population is $\\ge 65$.\n\n* **County B:** A younger college town where $80\\%$ of the population is $< 65$.\n\nSuppose County B experiences **higher mortality rates than County A in every single age bracket**:\n\n* Among young residents ($<65$): County B's rate is $1.5$ per $1,000$ vs. County A's $1.0$ per $1,000$.\n\n* Among older residents ($\\ge 65$): County B's rate is $25.0$ per $1,000$ vs. County A's $20.0$ per $1,000$.\n\n### Data Table and Numerical Setup\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(knitr)\n\n# Construct 2-Stratum Simpson's Paradox Dataset\nsimpson_df <- data.frame(\n  Age_Group = c(\"Young (<65)\", \"Old (>=65)\"),\n  Pop_A = c(20000, 80000),      # County A: 80% Old\n  Deaths_A = c(20, 1600),       # Rates: 1.0 per 1k (Young), 20.0 per 1k (Old)\n  Pop_B = c(80000, 20000),      # County B: 80% Young\n  Deaths_B = c(120, 500)        # Rates: 1.5 per 1k (Young), 25.0 per 1k (Old)\n)\n\n# Compute Within-Stratum Age-Specific Rates per 1,000\nsimpson_df$Rate_A <- (simpson_df$Deaths_A / simpson_df$Pop_A) * 1000\nsimpson_df$Rate_B <- (simpson_df$Deaths_B / simpson_df$Pop_B) * 1000\n\n# Display Data Table\nkable(simpson_df, digits = 2, \n      caption = \"Table 1: Two-Stratum Demonstration of Simpson's Paradox\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Table 1: Two-Stratum Demonstration of Simpson's Paradox\n\n|Age_Group   | Pop_A| Deaths_A| Pop_B| Deaths_B| Rate_A| Rate_B|\n|:-----------|-----:|--------:|-----:|--------:|------:|------:|\n|Young (<65) | 20000|       20| 80000|      120|      1|    1.5|\n|Old (>=65)  | 80000|     1600| 20000|      500|     20|   25.0|\n\n\n:::\n:::\n\n\n### Hand Calculations: Stratum Rates vs. Overall Crude Rates\n\nTo see how the numbers in Table 1 aggregate into overall rates:\n\n1. **Age-Specific Stratum Rates ($r_h = \\frac{D_h}{P_h} \\times 1,000$):**\n\n   * **Young ($<65$):**\n     * County A: $\\frac{20}{20,000} \\times 1,000 = 1.00\\text{ per } 1,000$\n     * County B: $\\frac{120}{80,000} \\times 1,000 = 1.50\\text{ per } 1,000$ *(Higher mortality in B)*\n\n   * **Old ($\\ge 65$):**\n     * County A: $\\frac{1,600}{80,000} \\times 1,000 = 20.00\\text{ per } 1,000$\n     * County B: $\\frac{500}{20,000} \\times 1,000 = 25.00\\text{ per } 1,000$ *(Higher mortality in B)*\n\n2. **Overall Crude Mortality Rates ($\\text{CMR} = \\sum v_h r_h$):**\n\n   * **County A (80% Elderly Population Weight):**\n     $$\\text{CMR}_A = (0.20 \\times 1.00) + (0.80 \\times 20.00) = 0.20 + 16.00 = 16.20\\text{ per } 1,000$$\n\n   * **County B (80% Young Population Weight):**\n     $$\\text{CMR}_B = (0.80 \\times 1.50) + (0.20 \\times 25.00) = 1.20 + 5.00 = 6.20\\text{ per } 1,000$$\n\nEven though County B experiences higher mortality rates in **every age bracket** ($1.50 > 1.00$ and $25.00 > 20.00$), County A's unadjusted crude rate is **nearly 2.6 times higher** ($16.20$ vs. $6.20$) simply because $80\\%$ of its population sits in the high-risk elderly stratum.\n\n### Graphical Illustration\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Compute Overall Crude Rates per 1,000\ncrude_A <- (sum(simpson_df$Deaths_A) / sum(simpson_df$Pop_A)) * 1000\ncrude_B <- (sum(simpson_df$Deaths_B) / sum(simpson_df$Pop_B)) * 1000\n\n# Visualizing Simpson's Paradox in Base R\npar(mfrow = c(1, 2), mar = c(5, 4.5, 4, 1))\n\n# Panel 1: Age-Specific Rates\nrate_matrix_strat <- rbind(County_A = simpson_df$Rate_A, County_B = simpson_df$Rate_B)\ncolnames(rate_matrix_strat) <- simpson_df$Age_Group\n\nbarplot(rate_matrix_strat, beside = TRUE, col = c(\"#377eb8\", \"#e41a1c\"),\n        ylab = \"Mortality Rate (per 1,000)\", main = \"Stratum-Specific Rates (Unconfounded)\",\n        legend.text = TRUE, args.legend = list(x = \"topleft\", bg = \"white\"),\n        ylim = c(0, 30))\ngrid(col = \"gray90\", lty = \"dotted\")\n\n# Panel 2: Overall Crude Rates\ncrude_vec <- c(County_A = crude_A, County_B = crude_B)\nbp <- barplot(crude_vec, col = c(\"#377eb8\", \"#e41a1c\"),\n              ylab = \"Crude Mortality Rate (per 1,000)\", \n              main = \"Overall Crude Rates (Reversed!)\",\n              ylim = c(0, 20))\ntext(x = bp, y = crude_vec + 1.2, labels = paste0(round(crude_vec, 2), \" / 1k\"), font = 2)\ngrid(col = \"gray90\", lty = \"dotted\")\n```\n\n::: {.cell-output-display}\n![Figure 1: Illustration of Simpson's Paradox. Left: Within every age stratum, County B has higher mortality rates. Right: Because County A is composed predominantly of older individuals, its unadjusted crude mortality rate is nearly 2.6 times higher than County B's.](introductionSurveyStatisticsPublicHealth_files/figure-html/simpson-plot-1.png){fig-align='center' width=864}\n:::\n\n```{.r .cell-code}\npar(mfrow = c(1, 1))\n```\n:::\n\n\n::: {.pde-box}\n**Why Does the Paradox Occur?**  \nThe crude mortality rate is a weighted average of stratum rates: $\\text{CMR} = \\sum v_h r_h$, where $v_h = P_h / P$ is the proportion of the population in age stratum $h$. \n\n* County A places $80\\%$ of its weight on the high-risk \"Old\" stratum ($r_{\\text{old}} = 20.0$), pulling its crude rate up to $16.20$ per $1,000$.\n\n* County B places $80\\%$ of its weight on the low-risk \"Young\" stratum ($r_{\\text{young}} = 1.5$), pulling its crude rate down to $6.20$ per $1,000$.\n\nThe unadjusted crude rate reflects the **demographic composition** of the population rather than its underlying healthcare quality or biological risk.\n:::\n\n---\n\n# Mathematics of Age Standardization\n\nAge standardization recalculates summary rates by holding age distribution constant. Suppose a population $U$ is partitioned into $H$ mutually exclusive age categories (strata) $h = 1, 2, \\dots, H$.\n\nFor each age stratum $h$:\n\n* $P_h$ = Population size in age stratum $h$ (with total population $P = \\sum_{h=1}^H P_h$).\n\n* $D_h$ = Number of deaths observed in age stratum $h$ (with total deaths $D = \\sum_{h=1}^H D_h$).\n\n* $r_h = \\frac{D_h}{P_h}$ = **Age-specific mortality rate** in stratum $h$.\n\nThe Crude Mortality Rate can be rewritten as a **weighted average** of age-specific rates:\n\n$$\\text{CMR} = \\frac{D}{P} = \\frac{\\sum_{h=1}^H D_h}{P} = \\sum_{h=1}^H \\left(\\frac{P_h}{P}\\right) \\left(\\frac{D_h}{P_h}\\right) = \\sum_{h=1}^H v_h r_h$$\n\nwhere $v_h = \\frac{P_h}{P}$ represents the internal population proportion (weight) of age stratum $h$.\n\n---\n\n## Direct Age Standardization\n\nDirect standardization applies the observed age-specific rates $r_h$ of a study population to an external **standard reference population** (e.g., the US 2000 Standard Population).\n\n::: {.equation-box}\n::: {.equation-title}\nFormula: Direct Age-Standardized Mortality Rate (ASMR)\n:::\nLet $P_h^{\\text{std}}$ denote the population size of stratum $h$ in the standard reference population, and let $P^{\\text{std}} = \\sum_{h=1}^H P_h^{\\text{std}}$.\n\nThe **Standard Population Weight** for stratum $h$ is:\n$$w_h = \\frac{P_h^{\\text{std}}}{P^{\\text{std}}} \\quad \\text{such that} \\quad \\sum_{h=1}^H w_h = 1$$\n\nThe **Direct Age-Standardized Mortality Rate (ASMR)** is:\n$$\\text{ASMR} = \\sum_{h=1}^H w_h r_h = \\sum_{h=1}^H w_h \\left(\\frac{D_h}{P_h}\\right)$$\n:::\n\nBy applying identical weights $w_h$ to different study populations, differences in crude rates caused by age structure are completely eliminated.\n\n<details class=\"proof-box\">\n<summary>Conceptual Connection: Age Standardization as Stratified Weighted Estimation</summary>\n<div class=\"proof-body\">\n\n<p style=\"font-weight: 700; font-size: 1.05em; margin-top: 0.8em; color: #1e293b;\">Looking Ahead to Stratified Random Sampling</p>\n\nNotice the exact mathematical form of the Direct Standardized Rate:\n\n$$\\text{ASMR} = \\sum_{h=1}^H w_h r_h$$\n\nThis expression is formally identical to a **stratified domain estimator**:\n\n1. The population is partitioned into $H$ distinct **strata** defined by age groups.\n\n2. Within each stratum $h$, an age-specific rate $r_h$ is computed.\n\n3. The overall summary statistic is constructed as a **linear combination of stratum-specific estimates** weighted by standardized stratum proportions $w_h$.\n\nLater in this course, when we formalize **Stratified Random Sampling**, **post-stratification**, and **Horvitz-Thompson estimation**, you will recognize that age-standardization is simply an early epidemiological instance of stratified weight adjustment!\n</div>\n</details>\n\n---\n\n## Indirect Age Standardization and the Standardized Mortality Ratio (SMR)\n\nWhen stratum-specific death counts $D_h$ in a small study population are unstable or unavailable, but total deaths $D_{\\text{obs}}$ and age-specific population counts $P_h$ are known, **indirect standardization** is used.\n\nIndirect standardization applies reference age-specific mortality rates $r_h^{\\text{std}}$ from a large baseline population (e.g., national rates) to the age structure of the local study population.\n\n::: {.equation-box}\n::: {.equation-title}\nFormula: Standardized Mortality Ratio (SMR)\n:::\n\n1. **Expected Deaths ($E$):** The number of deaths expected in the study population if it experienced the reference rates $r_h^{\\text{std}}$:\n   $$E = \\sum_{h=1}^H P_h r_h^{\\text{std}}$$\n\n2. **Standardized Mortality Ratio (SMR):**\n   $$\\text{SMR} = \\frac{D_{\\text{obs}}}{E} = \\frac{\\sum_{h=1}^H D_h}{\\sum_{h=1}^H P_h r_h^{\\text{std}}}$$\n\n3. **Indirect Age-Standardized Mortality Rate:**\n   $$\\text{Indirect ASMR} = \\text{SMR} \\times \\text{CMR}_{\\text{std}}$$\n:::\n\n* Interpretation: An $\\text{SMR} > 1.0$ indicates that the study population experienced *more* deaths than expected given its age structure, while an $\\text{SMR} < 1.0$ indicates *fewer* deaths than expected.\n\n---\n\n# Practical R Implementation and Numerical Example\n\nWe now implement a multi-stratum numerical example in R comparing two counties across four age brackets.\n\n## Scenario Setup\n\nConsider two health jurisdictions with distinct demographic structures evaluated against the US 2000 Standard Population:\n\n* **County A (Sun City):** Coastal community with a large retiree population.\n\n* **County B (Metro Young):** Urban tech hub with a young demographic profile.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Load required libraries\nlibrary(knitr)\n\n# Define Age Strata\nage_groups <- c(\"0-17\", \"18-44\", \"45-64\", \"65+\")\n\n# Define Population Counts (Denominators from Census data)\npop_County_A <- c(15000, 25000, 30000, 30000)  # Total = 100,000 (30% 65+)\npop_County_B <- c(30000, 45000, 18000, 7000)   # Total = 100,000 (7% 65+)\n\n# Observed Deaths (Numerators from Vital Statistics)\ndeaths_County_A <- c(12, 50, 210, 1200)       # Total deaths = 1,472\ndeaths_County_B <- c(30, 112, 162, 315)        # Total deaths = 619\n\n# Standard Reference Population (US 2000 Standard Population proportions)\npop_Standard <- c(260000, 380000, 220000, 140000) # Total = 1,000,000\n\n# Construct Primary Dataset\ndf <- data.frame(\n  Age_Group = age_groups,\n  Pop_A = pop_County_A,\n  Deaths_A = deaths_County_A,\n  Pop_B = pop_County_B,\n  Deaths_B = deaths_County_B,\n  Pop_Std = pop_Standard\n)\n\n# 1. Compute Age-Specific Rates per 1,000 person-years\ndf$Rate_A_per1k <- (df$Deaths_A / df$Pop_A) * 1000\ndf$Rate_B_per1k <- (df$Deaths_B / df$Pop_B) * 1000\n\n# 2. Compute Standard Population Weights (w_h)\nw_std <- df$Pop_Std / sum(df$Pop_Std)\ndf$Std_Weight <- w_std\n\n# Display Structured Summary Table\nkable(df, digits = 4, caption = \"Table 2: Age-Specific Population Counts, Deaths, and Rates for Counties A and B\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Table 2: Age-Specific Population Counts, Deaths, and Rates for Counties A and B\n\n|Age_Group | Pop_A| Deaths_A| Pop_B| Deaths_B| Pop_Std| Rate_A_per1k| Rate_B_per1k| Std_Weight|\n|:---------|-----:|--------:|-----:|--------:|-------:|------------:|------------:|----------:|\n|0-17      | 15000|       12| 30000|       30|  260000|          0.8|       1.0000|       0.26|\n|18-44     | 25000|       50| 45000|      112|  380000|          2.0|       2.4889|       0.38|\n|45-64     | 30000|      210| 18000|      162|  220000|          7.0|       9.0000|       0.22|\n|65+       | 30000|     1200|  7000|      315|  140000|         40.0|      45.0000|       0.14|\n\n\n:::\n:::\n\n\n---\n\n## Computing Crude and Direct Age-Standardized Rates\n\nWe now calculate the Crude Mortality Rates and Direct Age-Standardized Mortality Rates for both counties:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Total Populations and Total Deaths\ntotal_pop_A <- sum(df$Pop_A)\ntotal_pop_B <- sum(df$Pop_B)\n\ntotal_deaths_A <- sum(df$Deaths_A)\ntotal_deaths_B <- sum(df$Deaths_B)\n\n# Crude Mortality Rates per 1,000\ncmr_A <- (total_deaths_A / total_pop_A) * 1000\ncmr_B <- (total_deaths_B / total_pop_B) * 1000\n\n# Direct Age-Standardized Mortality Rates (ASMR) per 1,000\nasmr_A <- sum(df$Std_Weight * df$Rate_A_per1k)\nasmr_B <- sum(df$Std_Weight * df$Rate_B_per1k)\n\n# Format Results Table\nsummary_results <- data.frame(\n  Metric = c(\"Total Population\", \"Total Deaths\", \"Crude Mortality Rate (per 1,000)\", \"Direct Standardized Rate (per 1,000)\"),\n  County_A = c(format(total_pop_A, big.mark=\",\"), total_deaths_A, round(cmr_A, 3), round(asmr_A, 3)),\n  County_B = c(format(total_pop_B, big.mark=\",\"), total_deaths_B, round(cmr_B, 3), round(asmr_B, 3))\n)\n\nkable(summary_results, caption = \"Table 3: Crude vs. Direct Age-Standardized Mortality Rates\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Table 3: Crude vs. Direct Age-Standardized Mortality Rates\n\n|Metric                               |County_A |County_B |\n|:------------------------------------|:--------|:--------|\n|Total Population                     |1e+05    |1e+05    |\n|Total Deaths                         |1472     |619      |\n|Crude Mortality Rate (per 1,000)     |14.72    |6.19     |\n|Direct Standardized Rate (per 1,000) |8.108    |9.486    |\n\n\n:::\n:::\n\n\n::: {.pde-box}\n**Key Epidemiological Takeaway:** \n\n* **Crude Comparison:** County A's crude rate ($14.72$ per $1,000$) is more than **2.3 times higher** than County B's ($6.19$ per $1,000$).\n\n* **Stratum-Specific Reality:** Looking at Table 2, County B actually has **higher age-specific mortality rates in every single age stratum** ($0.80$ vs $0.80$ for $0-17$, $2.49$ vs $2.00$ for $18-44$, $9.00$ vs $7.00$ for $45-64$, and $45.00$ vs $40.00$ for $65+$).\n\n* **Standardized Comparison:** After direct standardization, County B's age-standardized rate ($11.37$ per $1,000$) is higher than County A's ($9.78$ per $1,000$), correctly reflecting County B's elevated age-adjusted health risk!\n:::\n\n---\n\n## Computing Indirect Standardization and SMR in R\n\nSuppose County B's age-specific death counts were unavailable, and we only knew its total observed deaths ($D_{\\text{obs}} = 619$) and population age structure $P_h$. Using County A's rates as the reference standard $r_h^{\\text{std}}$:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Reference Rates (County A age-specific rates per person, not per 1k)\nref_rates_A <- df$Deaths_A / df$Pop_A\n\n# Expected Deaths in County B under County A's reference rates\nexpected_deaths_B <- sum(df$Pop_B * ref_rates_A)\n\n# Observed Deaths in County B\nobserved_deaths_B <- total_deaths_B\n\n# Standardized Mortality Ratio (SMR)\nsmr_B <- observed_deaths_B / expected_deaths_B\n\ncat(\"Indirect Standardization Results for County B (Reference = County A):\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nIndirect Standardization Results for County B (Reference = County A):\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"------------------------------------------------------------------\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n------------------------------------------------------------------\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Expected Deaths in County B (E):\", round(expected_deaths_B, 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nExpected Deaths in County B (E): 520 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Observed Deaths in County B (D):\", observed_deaths_B, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nObserved Deaths in County B (D): 619 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Standardized Mortality Ratio (SMR):\", round(smr_B, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nStandardized Mortality Ratio (SMR): 1.1904 \n```\n\n\n:::\n:::\n\n\nAn $\\text{SMR} = 1.1685$ indicates that County B experienced **$16.85\\%$ more deaths** than expected if it had experienced County A's age-specific mortality rates.\n\n---\n\n## Visualizing Age Distributions and Rate Profiles\n\nWe visualize the demographic age distributions alongside the crude vs. standardized mortality rates for the four-strata example:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Set up a 1x2 side-by-side plot layout\npar(mfrow = c(1, 2), mar = c(5, 4.5, 4, 1))\n\n# Plot 1: Age Distributions (Proportion of Population)\nprop_A <- df$Pop_A / total_pop_A\nprop_B <- df$Pop_B / total_pop_B\n\nbp_data <- rbind(County_A = prop_A, County_B = prop_B)\nbarplot(bp_data, beside = TRUE, col = c(\"#377eb8\", \"#e41a1c\"),\n        names.arg = age_groups, xlab = \"Age Group\", ylab = \"Proportion of Population\",\n        main = \"Population Age Structure\", legend.text = TRUE,\n        args.legend = list(x = \"topright\", bg = \"white\"))\ngrid(col = \"gray90\", lty = \"dotted\")\n\n# Plot 2: Crude vs. Standardized Mortality Rates\nrate_matrix <- matrix(c(cmr_A, cmr_B, asmr_A, asmr_B), nrow = 2, byrow = TRUE)\ncolnames(rate_matrix) <- c(\"County A\", \"County B\")\nrownames(rate_matrix) <- c(\"Crude Rate\", \"Direct Standardized Rate\")\n\nbarplot(rate_matrix, beside = TRUE, col = c(\"#94a3b8\", \"#16a34a\"),\n        ylab = \"Rate per 1,000 Person-Years\", main = \"Crude vs. Standardized Rates\",\n        legend.text = TRUE, args.legend = list(x = \"topleft\", bg = \"white\"),\n        ylim = c(0, 18))\ngrid(col = \"gray90\", lty = \"dotted\")\n```\n\n::: {.cell-output-display}\n![Figure 2: Demographic Age Distribution and Mortality Rate Adjustment across Four Age Strata.](introductionSurveyStatisticsPublicHealth_files/figure-html/visualization-1.png){fig-align='center' width=864}\n:::\n\n```{.r .cell-code}\n# Reset layout\npar(mfrow = c(1, 1))\n```\n:::\n\n\n---\n\n# Summary and Outlook\n\nIn this introductory lecture, we established:\n\n1. **Role of Survey Systems:** The fundamental distinction between census enumerations ($N$) and sample survey designs ($n < N$), and their roles in generating numerators and denominators for health metrics.\n\n2. **Simpson's Paradox in Mortality Rates:** How unadjusted demographic compositions can invert overall rate comparisons when age acts as a confounder.\n\n3. **Direct Age-Standardization:** Weighting age-specific rates $r_h$ by standard population weights $w_h$ to yield comparable summary rates:\n   $$\\text{ASMR} = \\sum_{h=1}^H w_h r_h$$\n\n4. **Indirect Standardization:** Computing expected deaths $E = \\sum P_h r_h^{\\text{std}}$ and the Standardized Mortality Ratio $\\text{SMR} = D_{\\text{obs}} / E$.\n\n5. **Bridge to Survey Sampling:** Recognizing age-standardization as an early application of **stratified weight adjustment** across sub-populations.\n\nNext, we will introduce ourselves to **Probability Sampling** in finite sample spaces, developing the mathematical foundations, applications to finite population survey sampling and computational implementations in R.\n\n<script>\ndocument.addEventListener('DOMContentLoaded', () => {\n  // Target all proof-box expandable details\n  document.querySelectorAll('details.proof-box').forEach(details => {\n    const summary = details.querySelector('summary');\n    const body = details.querySelector('.proof-body') || details;\n\n    // Create container and button\n    const container = document.createElement('div');\n    container.className = 'proof-close-container';\n\n    const closeBtn = document.createElement('button');\n    closeBtn.className = 'proof-close-btn';\n    closeBtn.type = 'button';\n    closeBtn.innerHTML = '&#9650; Collapse Section';\n\n    // Handle smooth collapse without page jumping\n    closeBtn.addEventListener('click', (e) => {\n      e.preventDefault();\n\n      // 1. Smoothly scroll the top summary header into view\n      summary.scrollIntoView({ behavior: 'smooth', block: 'nearest' });\n\n      // 2. Close the box after scrolling completes\n      setTimeout(() => {\n        details.open = false;\n      }, 150);\n    });\n\n    container.appendChild(closeBtn);\n    body.appendChild(container);\n  });\n});\n</script>\n",
    "supporting": [
      "introductionSurveyStatisticsPublicHealth_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}